# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  dreapi:
    image: dreapi
    build:
      context: .
      dockerfile: src/DRE.Api/Dockerfile
    ports:
      - 5286:5286
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
