version: '3'

services:
  app:
    # Using a Dockerfile is optional, but included for completeness.
    build:
      context: .
      dockerfile: Dockerfile
    # enable internet in container
    dns:
        - 8.8.8.8
        - 4.4.4.4

      # [Optional] You can use build args to set options. e.g. 'VARIANT' below affects the image in the Dockerfile
      # args:
      #   VARIANT: buster

    volumes:
      # This is where VS Code should expect to find your project's source code and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/workspace:cached

    # Without that line dev continer launch fails
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

    # Runs app on the same network as the service container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:another-service

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mssql:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=yourStrong(!)Password
        - MSSQL_PID=Express
    volumes:
        - ../volumes/mssql:/var/opt/mssql/data